[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
anyhow = "1.0.98"
envy = "0.4.2"
sea-orm = "1.1.14"
serde = { version = "1.0.219", features = ["derive"] }

