name: Security Vulnerability
description: Report a security vulnerability (Please use private disclosure for critical issues)
title: "[SECURITY] "
labels: ["security", "critical"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **SECURITY NOTICE** ⚠️

        For critical security vulnerabilities, please report privately by emailing security@company.com
        instead of creating a public issue.

        Only use this template for non-critical security improvements or public discussions.

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this security issue?
      options:
        - Low - Security improvement suggestion
        - Medium - Minor security issue
        - High - Significant security concern (consider private disclosure)
        - Critical - Immediate security threat (use private disclosure)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Security Issue Description
      description: Describe the security concern
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could happen if this issue is exploited?
    validations:
      required: true

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: How do you suggest we address this?

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: I have not disclosed this vulnerability publicly
          required: true
        - label: I understand that critical vulnerabilities should be reported privately
          required: true
